plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id "maven-publish"
    id 'jacoco'
    id "com.github.spotbugs" version "5.0.14"
    id "io.freefair.lombok" version "8.13.1"
    id 'checkstyle'
    id 'pmd'
}

group = 'com.audition'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '22'
targetCompatibility = '22'

apply from: "$rootProject.projectDir/config/code-analysis.gradle"

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2025.0.0")
    set('logbackVersion', "1.5.18")
    set('slf4jVersion', "2.0.5")
    set('springdocVersion', "2.8.13")
    set('telemetryVersion', '1.41.0')
}

dependencies {

    // TODO Clean up unused dependencies. Add comments on consideration on any improvements you made.
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.boot:spring-boot-starter-aop"
    implementation "io.micrometer:micrometer-tracing-bridge-brave"
    implementation "io.micrometer:micrometer-tracing"
    implementation "io.micrometer:micrometer-registry-prometheus"
    implementation "io.micrometer:context-propagation"
    implementation "org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j"
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

    developmentOnly "org.springframework.boot:spring-boot-devtools"
    runtimeOnly "io.micrometer:micrometer-registry-prometheus"


    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    implementation "ch.qos.logback:logback-core:${logbackVersion}"
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'

    implementation "io.opentelemetry:opentelemetry-api:${telemetryVersion}"
    implementation "io.opentelemetry:opentelemetry-sdk:${telemetryVersion}"
    // provides ConfigProperties bean
    implementation "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:${telemetryVersion}"
    // exporter (OTLP for example)
    implementation "io.opentelemetry:opentelemetry-exporter-otlp:${telemetryVersion}"
    // Spring Boot starter (ties everything together)
    implementation "io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter:2.10.0"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "io.projectreactor:reactor-test"

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

checkstyle {
    toolVersion = '10.20.0' // latest stable version
    configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
}

task prepareGitHooks(type: Copy) {
    from "$projectDir/git-hooks"
    into "$projectDir/.git/hooks"
    include "*"
}
tasks.matching { it.name != 'prepareGitHooks' }.all { Task task -> task.dependsOn prepareGitHooks }


tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(Checkstyle) {
    reports {
        xml.required = false
        html.required = true // easier to read report
    }
}
jacocoTestCoverageVerification {
    dependsOn test
}

check {
    dependsOn jacocoTestCoverageVerification
}

configurations.all {
    resolutionStrategy {
        force "org.ow2.asm:asm:9.6"
        force "org.ow2.asm:asm-tree:9.6"
    }
}
